import { useEffect, useState } from 'react';
import { Alert, Button, Form, Input, Modal, Select, Space, Table, Tag, Typography, message } from 'antd';
import { DeleteOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { enc, rmq } from '../api';
import { DangerConfirm } from '../components';

export default function Bindings(){
 const [vhosts,setVhosts]=useState<any[]>([]),[vhost,setVhost]=useState('/'),[rows,setRows]=useState<any[]>([]),[exchanges,setExchanges]=useState<any[]>([]),[queues,setQueues]=useState<any[]>([]);const[error,setError]=useState(''),[open,setOpen]=useState(false),[danger,setDanger]=useState<any>(null);const[form]=Form.useForm();
 const loadV=async()=>{const v=await rmq<any[]>('GET','/api/vhosts');setVhosts(v);if(!v.some(x=>x.name===vhost)&&v[0])setVhost(v[0].name)};const load=async()=>{try{const [b,e,q]=await Promise.all([rmq<any[]>('GET',`/api/bindings/${enc(vhost)}?page=1&page_size=500`),rmq<any[]>('GET',`/api/exchanges/${enc(vhost)}?page=1&page_size=500`),rmq<any[]>('GET',`/api/queues/${enc(vhost)}?page=1&page_size=500`)]);setRows(b);setExchanges(e.filter(x=>x.name));setQueues(q);setError('')}catch(e:any){setError(e.message)}};useEffect(()=>{loadV().catch(e=>setError(e.message))},[]);useEffect(()=>{if(vhost)load()},[vhost]);
 const create=async(v:any)=>{await rmq('POST',`/api/bindings/${enc(vhost)}/e/${enc(v.exchange)}/q/${enc(v.queue)}`,{routing_key:v.routingKey||'',arguments:{}});message.success('绑定已创建');setOpen(false);form.resetFields();load()};const del=async()=>{if(!danger)return;await rmq('DELETE',`/api/bindings/${enc(vhost)}/e/${enc(danger.source)}/q/${enc(danger.destination)}/${enc(danger.properties_key)}`);message.success('绑定已删除');setDanger(null);load()};
 return <Space direction="vertical" size={14} style={{width:'100%'}}><div className="page-head"><div><Typography.Title level={2}>绑定（Binding）</Typography.Title><Typography.Text type="secondary">展示 Exchange → Queue 路由关系。</Typography.Text></div><Space><Select style={{minWidth:170}} value={vhost} options={vhosts.map(x=>({label:x.name,value:x.name}))} onChange={setVhost}/><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>创建绑定</Button></Space></div>{error&&<Alert type="error" message={error}/>}<Table rowKey={(r,i)=>`${r.source}-${r.destination}-${r.properties_key}-${i}`} dataSource={rows.filter(r=>r.destination_type==='queue')} scroll={{x:900}} columns={[{title:'来源 Exchange',dataIndex:'source',render:v=><Tag>{v||'(默认交换机)'}</Tag>},{title:'目标 Queue',dataIndex:'destination'},{title:'Routing Key',dataIndex:'routing_key',render:v=><Typography.Text code>{v||'(空)'}</Typography.Text>},{title:'属性键',dataIndex:'properties_key',ellipsis:true},{title:'操作',render:(_,r)=><Button size="small" danger icon={<DeleteOutlined/>} disabled={!r.source} onClick={()=>setDanger(r)}>删除</Button>}]} />
 <Modal open={open} title={`在 ${vhost} 创建 Exchange → Queue 绑定`} okText="创建" onOk={()=>form.submit()} onCancel={()=>setOpen(false)}><Form form={form} layout="vertical" onFinish={create}><Form.Item name="exchange" label="Exchange" rules={[{required:true}]}><Select showSearch options={exchanges.map(x=>({label:`${x.name} (${x.type})`,value:x.name}))}/></Form.Item><Form.Item name="queue" label="Queue" rules={[{required:true}]}><Select showSearch options={queues.map(x=>({label:x.name,value:x.name}))}/></Form.Item><Form.Item name="routingKey" label="Routing Key"><Input/></Form.Item></Form></Modal><DangerConfirm open={!!danger} title="删除绑定" resource={danger?`${danger.source} -> ${danger.destination}`:''} description="删除后消息将不再按此 Binding 路由。" onCancel={()=>setDanger(null)} onConfirm={del}/></Space>
}
