import { useEffect, useState } from 'react';
import { Alert, Button, Form, Input, Modal, Select, Space, Switch, Table, Tag, Typography, message } from 'antd';
import { DeleteOutlined, PlusOutlined, ReloadOutlined, SendOutlined } from '@ant-design/icons';
import { enc, rmq } from '../api';
import { DangerConfirm } from '../components';
import type { ExchangeInfo } from '../types';

export default function Exchanges(){
 const [vhosts,setVhosts]=useState<any[]>([]),[vhost,setVhost]=useState('/'),[rows,setRows]=useState<ExchangeInfo[]>([]); const [error,setError]=useState(''),[loading,setLoading]=useState(false),[createOpen,setCreateOpen]=useState(false); const [pub,setPub]=useState<ExchangeInfo|null>(null),[danger,setDanger]=useState<ExchangeInfo|null>(null); const [form]=Form.useForm(),[pubForm]=Form.useForm();
 const loadV=async()=>{const v=await rmq<any[]>('GET','/api/vhosts');setVhosts(v);if(!v.some(x=>x.name===vhost)&&v[0])setVhost(v[0].name)}; const load=async()=>{setLoading(true);try{setRows(await rmq('GET',`/api/exchanges/${enc(vhost)}?page=1&page_size=500`));setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}; useEffect(()=>{loadV().catch(e=>setError(e.message))},[]);useEffect(()=>{if(vhost)load()},[vhost]);
 const create=async(v:any)=>{await rmq('PUT',`/api/exchanges/${enc(vhost)}/${enc(v.name)}`,{type:v.type,durable:!!v.durable,auto_delete:!!v.auto_delete,internal:false,arguments:{}});message.success('交换机已创建');setCreateOpen(false);form.resetFields();load()};
 const publish=async(v:any)=>{if(!pub)return;const r:any=await rmq('PUT',`/api/exchanges/${enc(pub.vhost)}/${enc(pub.name)}/publish`,{properties:{content_type:v.contentType||'text/plain'},routing_key:v.routingKey||'',payload:v.payload||'',payload_encoding:'string'});message.success(r?.routed?'消息已路由到至少一个队列':'消息已发布，但没有匹配到队列');setPub(null);pubForm.resetFields()};
 const del=async()=>{if(!danger)return;await rmq('DELETE',`/api/exchanges/${enc(danger.vhost)}/${enc(danger.name)}?if-unused=true`);message.success('交换机已删除');setDanger(null);load()};
 return <Space direction="vertical" size={14} style={{width:'100%'}}><div className="page-head"><div><Typography.Title level={2}>交换机（Exchange）</Typography.Title><Typography.Text type="secondary">管理路由入口；HTTP 发布仅用于测试和排障。</Typography.Text></div><Space><Select style={{minWidth:170}} value={vhost} options={vhosts.map(x=>({label:x.name,value:x.name}))} onChange={setVhost}/><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setCreateOpen(true)}>创建交换机</Button></Space></div>{error&&<Alert type="error" message={error}/>}<Table rowKey={r=>`${r.vhost}:${r.name}`} loading={loading} dataSource={rows} scroll={{x:1000}} columns={[
 {title:'名称',dataIndex:'name',width:260,render:v=><Typography.Text strong>{v||'(默认交换机)'}</Typography.Text>},{title:'类型',dataIndex:'type',render:v=><Tag>{v}</Tag>},{title:'持久化',dataIndex:'durable',render:v=>v?'是':'否'},{title:'自动删除',dataIndex:'auto_delete',render:v=>v?'是':'否'},{title:'内部',dataIndex:'internal',render:v=>v?'是':'否'},
 {title:'操作',width:220,render:(_,r)=><Space><Button size="small" icon={<SendOutlined/>} disabled={!r.name} onClick={()=>setPub(r)}>发送测试</Button><Button size="small" danger icon={<DeleteOutlined/>} disabled={!r.name||r.name.startsWith('amq.')} onClick={()=>setDanger(r)}>删除</Button></Space>}
 ]}/>
 <Modal open={createOpen} title={`在 ${vhost} 创建交换机`} okText="创建" onOk={()=>form.submit()} onCancel={()=>setCreateOpen(false)}><Form form={form} layout="vertical" initialValues={{type:'direct',durable:true,auto_delete:false}} onFinish={create}><Form.Item name="name" label="交换机名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="type" label="类型"><Select options={['direct','topic','fanout','headers'].map(x=>({label:x,value:x}))}/></Form.Item><Form.Item name="durable" label="持久化" valuePropName="checked"><Switch/></Form.Item><Form.Item name="auto_delete" label="自动删除" valuePropName="checked"><Switch/></Form.Item></Form></Modal>
 <Modal open={!!pub} title={`发送测试消息：${pub?.name||''}`} okText="发送" onOk={()=>pubForm.submit()} onCancel={()=>setPub(null)}><Form form={pubForm} layout="vertical" onFinish={publish}><Form.Item name="routingKey" label="Routing Key"><Input/></Form.Item><Form.Item name="contentType" label="Content-Type" initialValue="application/json"><Input/></Form.Item><Form.Item name="payload" label="消息内容" rules={[{required:true}]}><Input.TextArea rows={8}/></Form.Item></Form></Modal>
 <DangerConfirm open={!!danger} title="删除交换机" resource={danger?.name||''} description="仅在交换机未被使用时删除。内置 amq.* 和默认交换机不可在此删除。" onCancel={()=>setDanger(null)} onConfirm={del}/></Space>
}
