import { useEffect, useState } from 'react';
import { Alert, Button, Form, Input, Modal, Select, Space, Table, Tag, Typography, message } from 'antd';
import { DeleteOutlined, KeyOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { enc, rmq } from '../api';
import { DangerConfirm } from '../components';

export default function Users(){const[users,setUsers]=useState<any[]>([]),[vhosts,setVhosts]=useState<any[]>([]),[permissions,setPermissions]=useState<any[]>([]),[error,setError]=useState(''),[open,setOpen]=useState(false),[permUser,setPermUser]=useState<any>(null),[danger,setDanger]=useState<any>(null);const[form]=Form.useForm(),[permForm]=Form.useForm();const load=async()=>{try{const[u,v,p]=await Promise.all([rmq<any[]>('GET','/api/users'),rmq<any[]>('GET','/api/vhosts'),rmq<any[]>('GET','/api/permissions')]);setUsers(u);setVhosts(v);setPermissions(p);setError('')}catch(e:any){setError(e.message)}};useEffect(()=>{load()},[]);const create=async(v:any)=>{await rmq('PUT',`/api/users/${enc(v.username)}`,{password:v.password,tags:(v.tags||[]).join(',')});message.success('用户已创建');setOpen(false);form.resetFields();load()};const setPerm=async(v:any)=>{if(!permUser)return;await rmq('PUT',`/api/permissions/${enc(v.vhost)}/${enc(permUser.name)}`,{configure:v.configure,write:v.write,read:v.read});message.success('权限已设置');setPermUser(null);permForm.resetFields();load()};const del=async()=>{if(!danger)return;await rmq('DELETE',`/api/users/${enc(danger.name)}`);message.success('用户已删除');setDanger(null);load()};
 return <Space direction="vertical" size={14} style={{width:'100%'}}><div className="page-head"><div><Typography.Title level={2}>用户与权限</Typography.Title><Typography.Text type="secondary">业务账户建议不设置 administrator 标签，只授予所需 VHost 权限。</Typography.Text></div><Space><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>创建用户</Button></Space></div>{error&&<Alert type="error" message={error}/>}<Table rowKey="name" dataSource={users} scroll={{x:1050}} expandable={{expandedRowRender:(u)=><Table size="small" pagination={false} rowKey={r=>`${r.vhost}-${r.user}`} dataSource={permissions.filter(p=>p.user===u.name)} columns={[{title:'VHost',dataIndex:'vhost'},{title:'Configure',dataIndex:'configure'},{title:'Write',dataIndex:'write'},{title:'Read',dataIndex:'read'}]}/>} } columns={[{title:'用户名',dataIndex:'name',render:v=><Typography.Text strong>{v}</Typography.Text>},{title:'标签',dataIndex:'tags',render:(v:any[])=>v?.length?v.map(x=><Tag key={x}>{x}</Tag>):<Tag>无</Tag>},{title:'密码哈希算法',dataIndex:'hashing_algorithm',ellipsis:true},{title:'操作',width:220,render:(_,r)=><Space><Button size="small" icon={<KeyOutlined/>} onClick={()=>{setPermUser(r);permForm.setFieldsValue({vhost:vhosts[0]?.name||'/',configure:'.*',write:'.*',read:'.*'})}}>设置权限</Button><Button size="small" danger icon={<DeleteOutlined/>} onClick={()=>setDanger(r)}>删除</Button></Space>}]} />
 <Modal open={open} title="创建 RabbitMQ 用户" okText="创建" onOk={()=>form.submit()} onCancel={()=>setOpen(false)}><Form form={form} layout="vertical" onFinish={create}><Form.Item name="username" label="用户名" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="password" label="密码" rules={[{required:true,min:12,message:'建议至少 12 位'}]}><Input.Password autoComplete="new-password"/></Form.Item><Form.Item name="tags" label="Management 标签"><Select mode="multiple" allowClear options={['administrator','monitoring','policymaker','management'].map(x=>({label:x,value:x}))} placeholder="业务账户通常留空"/></Form.Item></Form></Modal>
 <Modal open={!!permUser} title={`设置权限：${permUser?.name||''}`} okText="保存权限" onOk={()=>permForm.submit()} onCancel={()=>setPermUser(null)}><Form form={permForm} layout="vertical" onFinish={setPerm}><Form.Item name="vhost" label="VHost" rules={[{required:true}]}><Select options={vhosts.map(x=>({label:x.name,value:x.name}))}/></Form.Item><Form.Item name="configure" label="Configure 正则" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="write" label="Write 正则" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="read" label="Read 正则" rules={[{required:true}]}><Input/></Form.Item></Form></Modal>
 <DangerConfirm open={!!danger} title="删除用户" resource={danger?.name||''} description="该用户将立即无法建立新的 RabbitMQ 连接；现有连接可能需要主动断开。" onCancel={()=>setDanger(null)} onConfirm={del}/></Space>}
