import { useState } from 'react';
import { Alert, Button, Card, Checkbox, Form, Input, InputNumber, Select, Space, Typography } from 'antd';
import { ApiError, login } from './api';

export default function Login({ onSuccess }: { onSuccess: (session:any)=>void }) {
  const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const submit=async(v:any)=>{setLoading(true);setError('');try{const s=await login(v);onSuccess(s)}catch(e){setError(e instanceof ApiError?e.message:String(e))}finally{setLoading(false)}};
  return <div className="login-page"><div className="login-glow"/><Card className="login-card" bordered={false}><Space direction="vertical" size={4} style={{width:'100%',marginBottom:22}}><div className="brand-mark">RMQ</div><Typography.Title level={2} style={{margin:0}}>RabbitMQ 中文控制台</Typography.Title><Typography.Text type="secondary">本地运行 · 中文管理 · 凭据仅保存在当前 Node 进程内存</Typography.Text></Space>{error&&<Alert type="error" showIcon message={error} style={{marginBottom:16}}/>}<Form layout="vertical" initialValues={{name:'家庭 NAS RabbitMQ',protocol:'http',host:'192.168.6.60',managementPort:15672,amqpPort:5672,allowInsecureTls:false}} onFinish={submit}>
    <Form.Item name="name" label="连接名称" rules={[{required:true}]}><Input/></Form.Item><div className="form-grid"><Form.Item name="protocol" label="协议"><Select options={[{label:'HTTP',value:'http'},{label:'HTTPS',value:'https'}]}/></Form.Item><Form.Item name="host" label="RabbitMQ IP / 域名" rules={[{required:true}]}><Input/></Form.Item></div><div className="form-grid"><Form.Item name="managementPort" label="Management 端口" rules={[{required:true}]}><InputNumber style={{width:'100%'}} min={1} max={65535}/></Form.Item><Form.Item name="amqpPort" label="AMQP 端口"><InputNumber style={{width:'100%'}} min={1} max={65535}/></Form.Item></div><Form.Item name="username" label="用户名" rules={[{required:true}]}><Input autoComplete="username"/></Form.Item><Form.Item name="password" label="密码" rules={[{required:true}]}><Input.Password autoComplete="current-password"/></Form.Item><Form.Item name="allowInsecureTls" valuePropName="checked"><Checkbox>HTTPS 时允许自签名/不受信任证书（仅可信内网使用）</Checkbox></Form.Item><Button htmlType="submit" type="primary" size="large" block loading={loading}>连接 RabbitMQ</Button></Form><Typography.Paragraph type="secondary" style={{fontSize:12,marginTop:16,marginBottom:0}}>提示：控制台使用 Management HTTP API（通常 15672）。AMQP 端口仅作为连接信息展示，不会从浏览器直接连接。</Typography.Paragraph></Card></div>
}
